name: 'Credentials scanning'
description: 'Scan source code to find if credentials have been hardcoded'
inputs:
  folderToScan:  # path
    description: 'The folder where to scan files'
    required: true
    default: '/src'
outputs:
  scanned-files: 
    description: "Number of files scanned"
    value: ${{ steps.scanned-files.outputs.filesNo }}
runs:
  using: "composite"
  steps: 
    - run: grep "password" . -R > ../result.txt
      shell: bash
      working-directory: ${{ inputs.folderToScan }}
    - id: scanned-files
      run: |
         NUMBER=$(wc -l result.txt)
         echo "::set-output name=filesNo::$(echo $NUMBER)"
      shell: bash
    - run: echo "I found  ${{ steps.step1.outputs.NUMBER}} dangerous files"
      shell: bash
