name: Test composite action

on:
  workflow_dispatch:
    inputs:
      folder:
        required: true 
        default: "src"
jobs:

  test:
    runs-on: ubuntu-latest

    steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - id: myCompositeAction
        uses: lgmorand/github-action-composite-credscanning@main
        with:
          folderToScan: "${{ github.event.inputs.folder }}"
          
      - run: echo "${{ env.COUNT }} files contains a password" 
        env:
          COUNT: ${{ steps.myCompositeAction.outputs.scanned-files }}
     
