name: Test composite action

on:
  workflow_dispatch:
    inputs:
      folder:
        required: true 
jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - id: composite
        uses: lgmorand/github-action-composite-credscanning@main
        with:
          folderToScan: "${{ github.event.inputs.folder }}"
